### ISSUE TITLE
block statistics stopped working with pihole version 5

### ISSUE THREAD

**Issue by deathiotb** [ZachChristensen28/TA-pihole_dns#2]
i believe it is due to the new log schema:

[VERSION 5]
May 16 13:11:18 dnsmasq[11378]: 75420 10.10.10.10/24286 gravity blocked device-metrics-us.amazon.com is 0.0.0.0

[VERSION 4]
May  6 03:59:37 dnsmasq[25248]: 3083698 10.10.10.10/41075 /etc/pihole/gravity.list device-metrics-us.amazon.com is 0.0.0.0

**Comment by ZachChristensen28** [comment]
Thanks for bringing this to my attention. I will look for a way to update the configs to satisfy both version formats.
