### ISSUE TITLE
Port Number not Changing When Setting Up Modular Inputs

### ISSUE THREAD

**Issue by andrewixl** [ZachChristensen28/TA-pihole_dns#56]
**Describe the bug**
When setting up modular inputs, I will set the api port to 8080 which is the same as the HTTP connection port to view the UI. In Splunk, though it seems to ignore that and only attempt to use port 80.

**To Reproduce**
1. Go to Splunk Addon and Add Account with API Port 8080
2. Click on Search and Search index=_internal sourcetype="tapiholedns:log"
3. Wait for attempt to occur.
4. See error: Starting new HTTP connection (1): xxx.xxx.xxx.xxx:80

**Expected behavior**
I expect the addon to follow the api port put in the account of 8080 and no use port 80

**Screenshots**

**Version (please complete the following information):**
 - Splunk Version: 9.1.0.2
 - Pi-hole Version core=5.16.2, FTL=5.22
 - TA_pihole_dns Version 1.3.2

**Additional context**

**Comment by ZachChristensen28** [comment]
Thanks for calling this out. It looks like I set this up in preparation for the Pi-hole v6 release but never finished it. I will get a fix and new update out shortly.

**Comment by andrewixl** [comment]
Thanks, not to sure if a rush is needed. I did figure out a work around. If you put a port in the hostname/ip field it seems to ignore the port field default of 80
